set(gca, ...
  'Box'         , 'on'     , ...
  'ticklabelInterpreter','latex',...
  'FontSize'   , 14 , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'ZMinorTick'  , 'on'      , ...
  'XColor'      , [.1 .1 .1], ...
  'YColor'      , [.1 .1 .1], ...
  'ZColor'      , [.1 .1 .1], ...
  'LineWidth'   , 0.5         );